name: 'Setup Environment'
description: 'Set up Node.js, install npm dependencies, set up .NET SDK, configure dependency caching, restore, and optionally build'
inputs:
  build:
    description: 'Whether to run builds (npm buildProd and dotnet build) after install/restore'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'src/**/package-lock.json'

    - name: Install microsoft-trydotnet dependencies
      shell: bash
      working-directory: src/microsoft-trydotnet
      run: npm ci

    - name: Build microsoft-trydotnet
      if: inputs.build == 'true'
      shell: bash
      working-directory: src/microsoft-trydotnet
      run: npm run buildProd

    - name: Install microsoft-trydotnet-editor dependencies
      shell: bash
      working-directory: src/microsoft-trydotnet-editor
      run: npm ci

    - name: Build microsoft-trydotnet-editor
      if: inputs.build == 'true'
      shell: bash
      working-directory: src/microsoft-trydotnet-editor
      run: npm run buildProd

    - name: Install microsoft-trydotnet-styles dependencies
      shell: bash
      working-directory: src/microsoft-trydotnet-styles
      run: npm ci

    - name: Build microsoft-trydotnet-styles
      if: inputs.build == 'true'
      shell: bash
      working-directory: src/microsoft-trydotnet-styles
      run: npm run buildProd

    - name: Install microsoft-learn-mock dependencies
      shell: bash
      working-directory: src/microsoft-learn-mock
      run: npm ci

    - name: Build microsoft-learn-mock
      if: inputs.build == 'true'
      shell: bash
      working-directory: src/microsoft-learn-mock
      run: npm run buildProd

    - name: Set up .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Set up dependency caching for faster builds
      uses: actions/cache@v5
      with:
        path: |
          ~/.nuget/packages
          ${{ github.workspace }}/**/obj/project.assets.json
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          ${{ runner.os }}-nuget-

    - name: Restore .NET dependencies
      shell: bash
      run: dotnet restore

    - name: Build with dotnet
      if: inputs.build == 'true'
      shell: bash
      run: dotnet build -p:ContinuousIntegrationBuild=True -p:ReleaseDateAttribute=True --configuration Release --no-restore
